# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdevops',
                'doc_host': 'https://nitinverma78.github.io',
                'git_url': 'https://github.com/nitinverma78/nbdevops',
                'lib_path': 'nbdevops'},
  'syms': {'nbdevops.core': {'nbdevops.core.say_hello': ('setup.html#say_hello', 'nbdevops/core.py')}}}
